networks:
  local:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1280
services:
  api:
    container_name: receipt-processor
    build:
      context: .
    networks:
    - local
    ports:
    - "8080:8080"
    environment:
      ENV: dev
