networks:
  local:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1280
services:
  api:
    container_name: api
    build:
      context: .
      target: api
    networks:
    - local
    ports:
    - 8080:8080
    environment:
      &env
      PORT: 8080
      RECEIPT_QUEUE: receipt_processor
      RECEIPT_DATABASE: receipt_database
      REDIS_HOST: redis
  backend:
    container_name: backend
    build:
      context: .
      target: backend
    networks:
    - local
    environment:
      <<: *env
  redis:
    container_name: redis
    image: redis
    restart: always
    networks:
    - local
    ports:
    - 6379:6379
 